config/routes.rb
Rails.application.routes.draw do
  get 'check_answers/correct'
  get 'check_answers/incorrect'
  get 'math_functions/main'
  get 'math_functions/sum'
  get 'math_functions/minus'
  get 'math_functions/division'
  get 'math_functions/multiplication'
  post 'check_answers/correct'
  post 'check_answers/incorrect'
  post 'math_functions/main'

  root 'math_functions#main'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/check_answers_controller.rb
class CheckAnswersController < ApplicationController
  def correct
    @text = "Congratulations! You are a genius"
  end

  def incorrect
    @text = "Offf... Better luck next time"
  end
end

app/controllers/math_functions_controller.rb
class MathFunctionsController < ApplicationController

  before_action :fake_results, only: [:sum, :minus, :division, :multiplication, :main]

  def main
  end

  def sum
    @first = rand(100)
    @second = rand(100)
    @result = @first + @second
  end

  def minus
    @first = rand(100)
    @second = rand(100)
    @result = @first - @second
  end

  def division
    @first = rand(100)
    @second = rand(100)
    @result = @first / @second
  end

  def multiplication
    @first = rand(10)
    @second = rand(10)
    @result = @first * @second
  end

  def fake_results
    @resultFake1 = rand(150)
    @resultFake2 = rand(150)
    @resultFake3 = rand(150)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/check_answers_helper.rb
module CheckAnswersHelper
end

app/helpers/math_functions_helper.rb
module MathFunctionsHelper
end

app/views/check_answers/correct.html.erb
<div class="correct_class_design">
<h1>Congratulations</h1>
<body>
<p><%= @text %></p>
<br>
<%= button_to "Go back to main page", math_functions_main_path, method: :post %>
</body>
</div>

app/views/check_answers/incorrect.html.erb
<div class="incorrect_class_design">
<h1>Unlucky</h1>
<p><%= @text %></p>
<br>
<%= button_to "Go back to main page", math_functions_main_path, method: :post %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskFive</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/math_functions/division.html.erb
<div class="math_design">
<h1>This is our Division Function</h1>
<p>Please select the correct answer</p>
<p><%= @first %> / <%= @second %> =</p>
<br>
<%= button_to @result, check_answers_correct_path, method: :post %>
<br>
<%= button_to @resultFake1, check_answers_incorrect_path, method: :post %>
<br>
<%= button_to @resultFake2, check_answers_incorrect_path, method: :post %>
<br>
<%= button_to @resultFake3, check_answers_incorrect_path, method: :post %>
</div>

app/views/math_functions/main.html.erb
<div class="main_design">
<h1>This is our Main Page</h1>
<p>Welcome</p>
<br>
<%= link_to "Go to Sum Functions", math_functions_sum_path %>
<br>
<%= link_to "Go to Minus Functions", math_functions_minus_path %>
<br>
<%= link_to "Go to Division Functions", math_functions_division_path %>
<br>
<%= link_to "Go to Multiplication Functions", math_functions_multiplication_path %>
</div>

app/views/math_functions/minus.html.erb
<div class="math_design">
<h1>This is our Minus Function</h1>
<p>Please select the correct answer</p>
<p><%= @first %> - <%= @second %> =</p>
<br>
<%= button_to @result, check_answers_correct_path, method: :post %>
<br>
<%= button_to @resultFake1, check_answers_incorrect_path, method: :post %>
<br>
<%= button_to @resultFake2, check_answers_incorrect_path, method: :post %>
<br>
<%= button_to @resultFake3, check_answers_incorrect_path, method: :post %>
</div>

app/views/math_functions/multiplication.html.erb
<div class="math_design">
<h1>This is our multiplication Function</h1>
<p>Please select the correct answer</p>
<p><%= @first %> * <%= @second %> =</p>
<br>
<%= button_to @result, check_answers_correct_path, method: :post %>
<br>
<%= button_to @resultFake1, check_answers_incorrect_path, method: :post %>
<br>
<%= button_to @resultFake2, check_answers_incorrect_path, method: :post %>
<br>
<%= button_to @resultFake3, check_answers_incorrect_path, method: :post %>
</div>

app/views/math_functions/sum.html.erb
<div class="math_design">
<h1>This is our Sum Function</h1>
<p>Please select the correct answer</p>
<p><%= @first %> + <%= @second %> =</p>
<br>
<%= button_to @result, check_answers_correct_path, method: :post %>
<br>
<%= button_to @resultFake1, check_answers_incorrect_path, method: :post %>
<br>
<%= button_to @resultFake2, check_answers_incorrect_path, method: :post %>
<br>
<%= button_to @resultFake3, check_answers_incorrect_path, method: :post %>
</div>